
name: DEPLOY_MAPPING_TASK

on:
  workflow_dispatch:
    inputs:
      committed_sha:
        description: "Hash to deploy"
        type: string
        required: true

env:
  IICS_LOGIN_URL: https://dm-us.informaticacloud.com
  IICS_POD_URL: https://usw5.dm-us.informaticacloud.com/saas

  IICS_USERNAME: ${{ secrets.IICS_USERNAME }}
  IICS_PASSWORD: ${{ secrets.IICS_PASSWORD }}
  UAT_IICS_USERNAME: ${{ secrets.UAT_IICS_USERNAME }}
  UAT_IICS_PASSWORD: ${{ secrets.UAT_IICS_PASSWORD }}

  COMMIT_HASH: ${{ github.event.inputs.committed_sha }}

jobs:
  dev_build:
    name: Review Development Code
    environment:
      name: development
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install python modules
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to development
        run: python ./scripts/infa_login.py

      - name: Test Committed Mapping Tasks
        run: python ./scripts/infa_get_updates.py

  uat_commit:
    name: Complete UAT Promotion
    environment:
      name: uat
    needs: dev_build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: Rameswar-git1/informatica_qa
          ref: refs/heads/UAT
          token: ${{ secrets.GH_TOKEN }}
          path: informatica_qa
          lfs: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install project modules
        run: npm install
        working-directory: ./informatica_qa

      - name: Build and release content
        run: npm run build
        working-directory: ./informatica_qa

      - name: Checkout promotion pipeline
        uses: actions/checkout@v4
        with:
          path: iics-promotion-pipeline

      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install python modules
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Set default Git user
        run: |
          git config --global user.email "Rameswara.Reddy@safelite.com"
          git config --global user.name "Rameswar-git1"

      - name: Commit changes to UAT
        run: |
          cd ./informatica_qa
          git fetch --all
          git cherry-pick --strategy=recursive -X theirs ${COMMIT_HASH}
          git push

      - name: Get latest UAT commit hash
        run: |
          cd ./informatica_qa
          git pull
          echo "UAT_COMMIT_HASH=$(git log -1 --pretty=format:%H)" >> $GITHUB_ENV

      - name: Login to UAT
        run: python ./iics-promotion-pipeline/scripts/infa_login.py

      - name: Sync and test UAT deployment
        run: python ./iics-promotion-pipeline/scripts/infa_update_and_test.py
