name: Promote Dev to UAT

on:
  workflow_dispatch:
    inputs:
      committed_sha:
        description: "Hash to deploy"
        required: true
        type: string

env:
  COMMIT_HASH: ${{ github.event.inputs.committed_sha }}
  IICS_LOGIN_URL: https://dm-us.informaticacloud.com
  IICS_POD_URL: https://usw5.dm-us.informaticacloud.com/saas
  IICS_USERNAME: ${{ secrets.IICS_USERNAME }}
  IICS_PASSWORD: ${{ secrets.IICS_PASSWORD }}
  UAT_IICS_USERNAME: ${{ secrets.UAT_IICS_USERNAME }}
  UAT_IICS_PASSWORD: ${{ secrets.UAT_IICS_PASSWORD }}

jobs:
  promote_to_uat:
    name: Promote Commit to UAT
    runs-on: ubuntu-latest
    environment: QA
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Set up Git
        run: |
          git config --global user.name "Brandon Bir"
          git config --global user.email "bbird@informatica.com"

      - name: Clone Source Repository (Rameswar-git1/informatica-dev)
        run: |
          git clone --branch main https://x-access-token:${GH_TOKEN}@github.com/Rameswar-git1/informatica-dev.git source-repo

      - name: Clone Target Repository (informatica_qa)
        run: |
          git clone --branch main https://x-access-token:${GH_TOKEN}@github.com/Rameswar-git1/informatica_qa.git target-repo

      - name: Cherry-pick Commit from Source and Push to Target
        run: |
          cd target-repo
          git remote add source ../source-repo
          git fetch source

          git cherry-pick --strategy=recursive -X theirs ${COMMIT_HASH} || {
            if git status | grep -q "both deleted and modified"; then
              echo "Conflict due to deleted vs modified files. Restoring modified versions."
              git restore --source=source/${COMMIT_HASH} .
              git add .
              git cherry-pick --continue
            elif git status | grep -q "nothing to commit, working tree clean"; then
              echo "Cherry-pick resulted in no changes. Skipping."
              git cherry-pick --skip
            else
              echo "Cherry-pick failed unexpectedly."
              exit 1
            fi
          }

          git push origin main

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install requests

      - name: Login to UAT
        run: python ./source-repo/scripts/infa_login.py

      - name: Sync and Test UAT Deployment
        run: python ./source-repo/scripts/infa_update_and_test.py
